### ISSUE TITLE
Linker args ordering

### ISSUE THREAD

**Issue by crunchex** [mezoni/ccompile#5]
Is there a way to set up the .yaml file in a project (the one that provides the compiler and linker args) such that the args can be manually positioned on the command line?

I've got a case where I'm trying to link in a system shared library and the flag to do so needs to be placed at the end of the line (or at least not near the beginning, with most other flags). See this: https://code.google.com/p/dart/issues/detail?id=22257#c4

And as a side question: is there a way to enable debug prints for getting the full line that will be passed into the compiler and linker?

**Comment by mezoni** [comment]
You can try again.
I was made changes in `ccompilers`.
From CHANGELOG.md:
```
0.2.8
The order of the arguments was modified. The user defined arguments goes now last
```

Also the `ccompile` now completely based on the `ccompilers`.
So, everything should works.

>> And as a side question: is there a way to enable debug prints for getting the full line that will be passed into the compiler and linker?

I added the logger to the `ProjectBuilder`.

Sample code from `example/example_build.dart`
```
    var logger = new Logger("Builder");
    logger.onRecord.listen((record) {
      try {
        var decoder = new JsonDecoder();
        var message = decoder.convert(record.message);
        if (message is Map) {
          if (message["operation"] == "run") {
            var parameters = message["parameters"];
            if (parameters is Map) {
              var executable = parameters["executable"];
              if (executable is String) {
                var arguments = parameters["arguments"];
                if (arguments is List) {
                  print("$executable ${arguments.join(" ")}");
                }
              }
            }
          }
        }

      } catch (e) {
      }
    });

    ProjectBuilder.logger = logger;
```

**Comment by crunchex** [comment]
Great, updated and working. Thanks!
