### ISSUE TITLE
DART_SDK is deprecated

### ISSUE THREAD

**Issue by martinsik** [mezoni/ccompile#6]
File [dart_utils.dart](https://github.com/mezoni/ccompile/blob/master/lib/src/dart_utils.dart) is using enviromental variable `DART_SDK` to find Dart SDK which is deprecated now.

[“DART_SDK” environment variable is officially removed?](http://stackoverflow.com/questions/26408682/dart-sdk-environment-variable-is-officially-removed)
https://github.com/dart-lang/sdk/issues/16994

It seems like [dart_sdk.dart from mezoni/ccompilers ](https://github.com/mezoni/ccompilers/blob/master/lib/src/dart_sdk.dart) is doing it the right way so maybe you can just swith to this one.

**Comment by mezoni** [comment]
This is an oversight.
The package `compile` already for a long time completely based (depends) on the package `ccompilers`.
Initially it was not.
Thank you. I will change it as you suggested.

**Comment by mezoni** [comment]
Done.
